apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-server
  template:
    metadata:
      labels:
        name: demo-server
    spec:
      containers:
        - image: arschles/xkcd:latest
          name: xkcd
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    name: demo-server
  type: ClusterIP
status:
  loadBalancer: { }

---
# kubectl label namespace default istio-injection=enabled