//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 XinYang

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleRuleSpec) DeepCopyInto(out *ScaleRuleSpec) {
	*out = *in
	if in.StableWindow != nil {
		in, out := &in.StableWindow, &out.StableWindow
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleRuleSpec.
func (in *ScaleRuleSpec) DeepCopy() *ScaleRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ScaleRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroScaledObject) DeepCopyInto(out *ZeroScaledObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroScaledObject.
func (in *ZeroScaledObject) DeepCopy() *ZeroScaledObject {
	if in == nil {
		return nil
	}
	out := new(ZeroScaledObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroScaledObject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroScaledObjectList) DeepCopyInto(out *ZeroScaledObjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZeroScaledObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroScaledObjectList.
func (in *ZeroScaledObjectList) DeepCopy() *ZeroScaledObjectList {
	if in == nil {
		return nil
	}
	out := new(ZeroScaledObjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroScaledObjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroScaledObjectSpec) DeepCopyInto(out *ZeroScaledObjectSpec) {
	*out = *in
	out.Service = in.Service
	out.Workload = in.Workload
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(ScaleRuleSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroScaledObjectSpec.
func (in *ZeroScaledObjectSpec) DeepCopy() *ZeroScaledObjectSpec {
	if in == nil {
		return nil
	}
	out := new(ZeroScaledObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroScaledObjectStatus) DeepCopyInto(out *ZeroScaledObjectStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroScaledObjectStatus.
func (in *ZeroScaledObjectStatus) DeepCopy() *ZeroScaledObjectStatus {
	if in == nil {
		return nil
	}
	out := new(ZeroScaledObjectStatus)
	in.DeepCopyInto(out)
	return out
}
