/*
Copyright 2022 XinYang

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kzscaler/kzscaler/pkg/apis/scaling/v1alpha1"
	scheme "github.com/kzscaler/kzscaler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ZeroScalersGetter has a method to return a ZeroScalerInterface.
// A group's client should implement this interface.
type ZeroScalersGetter interface {
	ZeroScalers(namespace string) ZeroScalerInterface
}

// ZeroScalerInterface has methods to work with ZeroScaler resources.
type ZeroScalerInterface interface {
	Create(ctx context.Context, zeroScaler *v1alpha1.ZeroScaler, opts v1.CreateOptions) (*v1alpha1.ZeroScaler, error)
	Update(ctx context.Context, zeroScaler *v1alpha1.ZeroScaler, opts v1.UpdateOptions) (*v1alpha1.ZeroScaler, error)
	UpdateStatus(ctx context.Context, zeroScaler *v1alpha1.ZeroScaler, opts v1.UpdateOptions) (*v1alpha1.ZeroScaler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ZeroScaler, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ZeroScalerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ZeroScaler, err error)
	ZeroScalerExpansion
}

// zeroScalers implements ZeroScalerInterface
type zeroScalers struct {
	client rest.Interface
	ns     string
}

// newZeroScalers returns a ZeroScalers
func newZeroScalers(c *ScalingV1alpha1Client, namespace string) *zeroScalers {
	return &zeroScalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the zeroScaler, and returns the corresponding zeroScaler object, and an error if there is any.
func (c *zeroScalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ZeroScaler, err error) {
	result = &v1alpha1.ZeroScaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("zeroscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ZeroScalers that match those selectors.
func (c *zeroScalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ZeroScalerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ZeroScalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("zeroscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested zeroScalers.
func (c *zeroScalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("zeroscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a zeroScaler and creates it.  Returns the server's representation of the zeroScaler, and an error, if there is any.
func (c *zeroScalers) Create(ctx context.Context, zeroScaler *v1alpha1.ZeroScaler, opts v1.CreateOptions) (result *v1alpha1.ZeroScaler, err error) {
	result = &v1alpha1.ZeroScaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("zeroscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(zeroScaler).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a zeroScaler and updates it. Returns the server's representation of the zeroScaler, and an error, if there is any.
func (c *zeroScalers) Update(ctx context.Context, zeroScaler *v1alpha1.ZeroScaler, opts v1.UpdateOptions) (result *v1alpha1.ZeroScaler, err error) {
	result = &v1alpha1.ZeroScaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("zeroscalers").
		Name(zeroScaler.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(zeroScaler).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *zeroScalers) UpdateStatus(ctx context.Context, zeroScaler *v1alpha1.ZeroScaler, opts v1.UpdateOptions) (result *v1alpha1.ZeroScaler, err error) {
	result = &v1alpha1.ZeroScaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("zeroscalers").
		Name(zeroScaler.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(zeroScaler).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the zeroScaler and deletes it. Returns an error if one occurs.
func (c *zeroScalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("zeroscalers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *zeroScalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("zeroscalers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched zeroScaler.
func (c *zeroScalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ZeroScaler, err error) {
	result = &v1alpha1.ZeroScaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("zeroscalers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
