name: Build Wasm
on:
  push:

jobs:
  build-wasm:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - name: Install Build Tools
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.22.0/tinygo_0.22.0_amd64.deb
          sudo dpkg -i tinygo_0.22.0_amd64.deb

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build wasm
        run: make build.wasm

      - name: Generate name
        run: echo WASMNAME=proxy-$(date +%s).wasm >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: wasm
          path: cmd/proxy/main.go.wasm

      - uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: cmd/proxy/main.go.wasm
          remote_path: ${{ env.WASMNAME }}
          clean: false