name: builf wasm
on:
  push:

jobs:
  build-wasm:
    name: Build examples
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.22.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      # TinyGo's release container does not have Make command.
      - name: Install Make
        run: apt install make

      - name: Build examples
        run: make build.wasm
      # upload wasm binary
      - uses: actions/upload-artifact@v2
        with:
          name: wasm
          path: cmd/proxy/main.go.wasm