name: builf wasm
on:
  push:

jobs:
  build-wasm:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.22.0/tinygo_0.22.0_amd64.deb
          sudo dpkg -i tinygo_0.22.0_amd64.deb

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Make
        run: apt install make

      - name: Build wasm
        run: make build.wasm

      - uses: actions/upload-artifact@v2
        with:
          name: wasm
          path: cmd/proxy/main.go.wasm